### ISSUE TITLE
Thumbnail Error - unable to download documents #4

### ISSUE THREAD

**Issue by Yogendralakshminarayan** [Selco-Foundation/e4h-incident-management#10]
**Describe the bug**
We are unable to access the documents or images in the ticket. The services are giving us a "Thumbnail error" message. Below is the screen shot

**To Reproduce**
1. Go to 'Inbox'
2. Click on 'any ticket ID'
3. Scroll down to Ticket details section or ticket time
4. Thumbnail not displaying the document image.

**Expected behavior**
System should display the thumbnail image and user should be able to donwload the image or document.

**Screenshots**
<img width="571" alt="Thumbnail issue" src="https://github.com/user-attachments/assets/b91b852b-e9fd-46f8-9571-a98f209bad65">

**Desktop (please complete the following information):**
 - OS: Windown
 - Browser: chrome
 - Version 129.0.6668.89

**Smartphone (please complete the following information):**
 - Device: ReadMe
 - OS: Anroid
 - Browser chrome
 - Version 129.0.6668.89

**Additional context**
None

**Comment by Yogendralakshminarayan** [comment]
Its Fixed @deepikaarora88 could you please provide details on what was the issue and how it was resolved from a tech persepctive. And we can close the issue

**Comment by deepikaarora88** [comment]
Interim issue with AWS S3 bucket document fetch which is resolved now.
