### ISSUE TITLE
Unable to access the System due to SSL Certification error #5

### ISSUE THREAD

**Issue by Yogendralakshminarayan** [Selco-Foundation/e4h-incident-management#11]
**Describe the bug**
System displays SSL certification error.

**To Reproduce**
1. Go to https://saura-emitra.selcofoundation.org
2. See error
" system diplays SSL certification error"

**Expected behavior**
Once user clicks on https://saura-emitra.selcofoundation.org
system naviagates to 
https://saura-emitra.selcofoundation.org/digit-ui/employee/user/language-selection

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version NA

**Smartphone (please complete the following information):**
 - Device: ReadMe
 - OS: Anroid
 - Browser Chrome
 - Version - NA

**Additional context**
None

**Comment by Yogendralakshminarayan** [comment]
Its Fixed @deepikaarora88 could you please provide details on what was the issue and how it was resolved from a tech persepctive. And we can close the issue

**Comment by deepikaarora88** [comment]
Added provided certificate and it worked!!
