### ISSUE TITLE
SLA when it reaches "0" days. On the Laptop Screen device it does not display 0 as a number. #1

### ISSUE THREAD

**Issue by Yogendralakshminarayan** [Selco-Foundation/e4h-incident-management#7]
**Describe the bug**

**To Reproduce**
1. Go to 'home page'
2. Click on 'Inbox '
3. Scroll down to 'Ticket ID'
4. SLA is blank when it reaches 0

**Expected behavior**
When the ticket reaches the SLA "0" system should be able to diplay "0" rather than blanl

**Screenshots**
<img width="593" alt="SLA0" src="https://github.com/user-attachments/assets/50cbdfef-45e1-4e75-b4e6-44d37cf518fa">

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [chrome]
 - Version 129.0.6668.89 

**Smartphone (please complete the following information):**
 - Device: [ReadMe]
 - OS: [Anroid]
 - Browser [chrome]
 - Version 129.0.6668.89 

**Additional context**
None

**Comment by Yogendralakshminarayan** [comment]
Its Fixed @deepikaarora88 could you please provide details on what was the issue and how it was resolved from a tech ppersepctive. And we can close the issue

**Comment by deepikaarora88** [comment]
added condition for sla days to reflect 0.
